language: python
sudo: required
services:
    - docker
python:
    - 3.6
before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce
install:
    - docker build -t bannsec/gallimaufry .
    - docker run -t -d --name gal bannsec/gallimaufry
    - docker exec -it -u gallimaufry gal bash -c '. ~/.virtualenvs/gallimaufry/bin/activate && cd /home/gallimaufry/gallimaufry/ && pip install .[dev]'
script:
    - docker exec -it -u gallimaufry gal bash -c '. ~/.virtualenvs/gallimaufry/bin/activate && cd /home/gallimaufry/gallimaufry/ && pytest --boxed -n 4 --cov=Gallimaufry tests'
