language: python
sudo: required
services:
    - docker
python:
    - 3.6
install:
    - docker build -t bannsec/gallimaufry .
    - docker run -d --name gal bannsec/gallimaufry
    - docker exec -it -u gallimaufry gal bash -c '. ~/.virtualenvs/gallimaufry/bin/activate && cd /home/gallimaufry/gallimaufry/ && pip install .[dev]'
script:
    - docker exec -it -u gallimaufry gal bash -c '. ~/.virtualenvs/gallimaufry/bin/activate && cd /home/gallimaufry/gallimaufry/ && pytest --boxed -n 4 --cov=Gallimaufry tests'
